# Generated by Django 5.1.6 on 2025-03-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обращения')),
                ('telegram_chat_id', models.PositiveIntegerField(null=True, verbose_name='ID чата в Telegram')),
                ('telegram_sent_message_id', models.PositiveIntegerField(null=True, verbose_name='ID сообщения в Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя в Telegram')),
                ('telegram_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя в Telegram')),
                ('telegram_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия в Telegram')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('inn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН')),
                ('text', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Текст обращения')),
                ('type', models.CharField(choices=[('GENERAL', 'Обратная связь'), ('CONTRACT_TEMPLATE_CONTRACTOR', 'Шаблон договора подрядчика'), ('CONTRACT_TEMPLATE_SUPPLIER', 'Шаблон договора поставщика')], default='GENERAL', max_length=255, verbose_name='Тип запроса')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('submitted', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('next_field', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=50, null=True)),
                ('text', models.TextField(blank=True, max_length=4096, null=True)),
                ('nav_text', models.CharField(default='-', max_length=255)),
                ('input_function', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('path', models.CharField(default=None, editable=False, max_length=1000, null=True)),
                ('button_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_nodes', to='tenders_bot.node')),
            ],
            options={
                'verbose_name': 'узел',
                'verbose_name_plural': 'узлы',
                'ordering': ['button_order'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='nodes_content/')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tenders_bot.node')),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_uploads/')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='tenders_bot.feedback')),
            ],
        ),
    ]
