# Generated by Django 5.1.6 on 2025-05-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'Обратная связь')], default='GENERAL', max_length=255, verbose_name='Тип запроса'),
        ),
    ]
